// Generated by https://quicktype.io

export interface User {
  id: string
  name: string
  email: string
  address: string
  role: string
}

export interface Balance {
  rawBalance: string
  balance: number
}
